# ----------------------------------------------
# Script Recorded by Ansys Electronics Desktop Version 2021.2.0
# 19:03:23  mar 22, 2025
# ----------------------------------------------
# -*- coding: utf-8 -*-

oProject = oDesktop.GetActiveProject()
oDesign = oProject.GetActiveDesign()
oEditor = oDesign.SetActiveEditor("3D Modeler")
oModule = oDesign.GetModule("BoundarySetup")
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
from math import sin, cos, pi


nome = 1
Lsub = 70
Wsub = 46
t= 0.017
H = 1.6
Wfeed = 1.485

ordem = 2
angulo1 = 60
angulo2 = 60
angulo3 = 60

perimetro = 45
perimetro2 = 45
perimetro3 = 45

esp = 0.4

t = 0.017
COR = "(41 140 189)"
altura_da_reta = 0
espessura = 1

distanciaFractalMicrofita = 0.15
distanciaEntreOsFractais1e2 = 2
distanciaEntreOsFractais2e3 = 2

#pontoinicial = [3-altura_e_largura+esp, 6-(altura_e_largura/2)]
radiano = pi / 180

raio = (perimetro)/((3*(4)**ordem)+(2*cos(angulo1*radiano)+2)**ordem)
raio2 = (perimetro2)/((3*(4)**ordem)+(2*cos(angulo2*radiano)+2)**ordem)
raio3 = (perimetro2)/((3*(4)**ordem)+(2*cos(angulo2*radiano)+2)**ordem)

distanciaCentroFractal = raio*((2*cos(angulo1*radiano)+2)**ordem)
distanciaCentroFractal2 = raio2*((2*cos(angulo2*radiano)+2)**ordem)
distanciaCentroFractal3 = raio2*((2*cos(angulo2*radiano)+2)**ordem)

pontoinicialY2 = (Lsub/2)-(distanciaCentroFractal2/2)
pontoinicialX2 = esp+(Wfeed/2)+distanciaFractalMicrofita

pontoinicialY = (Lsub/2)-(distanciaCentroFractal2/2)-(distanciaCentroFractal)-(distanciaEntreOsFractais1e2)-2*esp
pontoinicialX = esp+(Wfeed/2)+distanciaFractalMicrofita

pontoinicialY3 = (Lsub/2)-(distanciaCentroFractal2/2)+(distanciaCentroFractal2)+(distanciaEntreOsFractais2e3)+2*esp
pontoinicialX3 = esp+(Wfeed/2)+distanciaFractalMicrofita#

pontoinicial=[pontoinicialX,pontoinicialY]

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:distanciaEntreOsFractais1e2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(distanciaEntreOsFractais1e2)+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:distanciaEntreOsFractais2e3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(distanciaEntreOsFractais2e3)+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:radiano",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "pi/180"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:distanciaFractalMicrofita",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(distanciaFractalMicrofita)+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:ordem",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(ordem)
				]
			]
		]
	])
oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:esp",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(esp)+"mm"
				]
			]
		]
	])
oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:angulo1",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(angulo1)
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:angulo2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(angulo2)
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:angulo3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(angulo3)
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:perimetro",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(perimetro)
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:perimetro2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(perimetro2)
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:perimetro3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(perimetro3)
				]
			]
		]
	])



oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:raio",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(perimetro)/((3*(4)**ordem)+(2*cos(angulo1*radiano)+2)**ordem)"+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:raio2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(perimetro2)/((3*(4)**ordem)+(2*cos(angulo2*radiano)+2)**ordem)"+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:raio3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(perimetro3)/((3*(4)**ordem)+(2*cos(angulo3*radiano)+2)**ordem)"+"mm"
				]
			]
		]
	])



oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:Wsub",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(Wsub)+"mm"
				]
			]
		]
	])
oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:H",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(H)+"mm"
				]
			]
		]
	])
oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:Lsub",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(Lsub)+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:distanciaCentroFractal",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "raio*((2*cos(angulo1*radiano)+2)**ordem)"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:distanciaCentroFractal2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "raio2*((2*cos(angulo2*radiano)+2)**ordem)"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:distanciaCentroFractal3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "raio3*((2*cos(angulo3*radiano)+2)**ordem)"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:Wfeed",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(Wfeed)+"mm"
				]
			]
		]
	])
oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:t",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, str(t)+"mm"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:pontoinicialX2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "esp+(Wfeed/2)+distanciaFractalMicrofita"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:pontoinicialX",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "esp+(Wfeed/2)+distanciaFractalMicrofita"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:pontoinicialX3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "esp+(Wfeed/2)+distanciaFractalMicrofita"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:pontoinicialY2",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(Lsub/2)-(distanciaCentroFractal2/2)"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:pontoinicialY",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(Lsub/2)-(distanciaCentroFractal2/2)-(distanciaCentroFractal)-(distanciaEntreOsFractais1e2)-2*esp"
				]
			]
		]
	])

oDesign.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:LocalVariableTab",
			[
				"NAME:PropServers",
				"LocalVariables"
			],
			[
				"NAME:NewProps",
				[
					"NAME:pontoinicialY3",
					"PropType:="		, "VariableProp",
					"UserDef:="		, True,
					"Value:="		, "(Lsub/2)-(distanciaCentroFractal2/2)+(distanciaCentroFractal2)+(distanciaEntreOsFractais2e3)+2*esp"
				]
			]
		]
	])

#-------------------------------------------
def Cesaro_Fractal(ordem,b,pontoinicial=[0,0]):
    listapontos = []
    listapontos.append(("{}mm".format(pontoinicial[0]), "{}mm".format(pontoinicial[1]), "0mm"))
    grausinicial = ["0"]
    graus = []
    for c in range(0, ordem):
	    graus = []
	    graus.extend(grausinicial)
	    graus60 = [str(c)+"+(angulo"+b+"*pi/180)" for c in grausinicial]
	    graus.extend(graus60)
	    graus300 = [str(c)+"+(360*pi/180-(angulo"+b+"*pi/180))" for c in grausinicial]
	    graus.extend(graus300)
	    graus.extend(grausinicial)
	    grausinicial = []
	    grausinicial.extend(graus)


    lado2 = [str(c)+"+(90*pi/180)" for c in graus]
    lado3 = [str(c)+"+(180*pi/180)" for c in graus]
    lado4 = [str(c)+"+(270*pi/180)" for c in graus]

    graus.extend(lado2)
    graus.extend(lado3)
    #graus.extend(lado4)
    return graus


pontos2 = Cesaro_Fractal(ordem,"1",pontoinicial)
pontos = [['pontoinicialX','pontoinicialY','0mm']]

pontos21 = Cesaro_Fractal(ordem,"2",[pontoinicialX2,pontoinicialY2])
pontosn1 = [['pontoinicialX2','pontoinicialY2','0mm']]

pontos3 = Cesaro_Fractal(ordem,"3",[pontoinicialX3,pontoinicialY3])
pontosn3 = [['pontoinicialX3','pontoinicialY3','0mm']]

for c in range(0,len(pontos2)):
    pontos.append(["raio*cos("+pontos2[c]+")"+"+"+pontos[c][0],"raio*sin("+pontos2[c]+")"+"+"+pontos[c][1],'0mm'])

for c in range(0,len(pontos21)):
    pontosn1.append(["raio2*cos("+pontos21[c]+")"+"+"+pontosn1[c][0],"raio2*sin("+pontos21[c]+")"+"+"+pontosn1[c][1],'0mm'])

for c in range(0,len(pontos21)):
    pontosn3.append(["raio3*cos("+pontos3[c]+")"+"+"+pontosn3[c][0],"raio3*sin("+pontos3[c]+")"+"+"+pontosn3[c][1],'0mm'])

pontos.append(pontos[0])
pontosn1.append(pontosn1[0])
pontosn3.append(pontosn3[0])

def criar_pontos(pontos):
    polyline_points = ["NAME:PolylinePoints"]
    for ponto in pontos:
        polyline_points.append(
            [
                "NAME:PLPoint",
                "X:=", ponto[0],
                "Y:=", ponto[1],
                "Z:=", "0mm"
            ]
        )
    return polyline_points

def criar_segmentos(pontos):
    polyline_segments = ["NAME:PolylineSegments"]
    for i in range(len(pontos) - 1):
        polyline_segments.append(
            [
                "NAME:PLSegment",
                "SegmentType:=", "Line",
                "StartIndex:=", i,
                "EndIndex:=", i + 1
            ]
        )
    polyline_segments.append(
        [
            "NAME:PLSegment",
            "SegmentType:=", "Line",
            "StartIndex:=", len(pontos) - 1,
            "EndIndex:=", 0
        ]
    )
    return polyline_segments

oEditor.CreateBox(
	[
		"NAME:BoxParameters",
		"XPosition:="		, "-0.6mm",
		"YPosition:="		, "-0.8mm",
		"ZPosition:="		, "0mm",
		"XSize:="		, "1.6mm",
		"YSize:="		, "2mm",
		"ZSize:="		, "0.4mm"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Box1",
		"Flags:="		, "",
		"Color:="		, "(255 0 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])



oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DAttributeTab",
			[
				"NAME:PropServers",
				"Box1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Material",
					"Value:="		, "\"FR4_epoxy\""
				],
				[
					"NAME:Color",
					"R:="			, 64,
					"G:="			, 0,
					"B:="			, 128
				],
				[
					"NAME:Transparent",
					"Value:="		, 0
				],
				[
					"NAME:Name",
					"Value:="		, ""
				],
				[
					"NAME:Name",
					"Value:="		, "Substrato"
				]
			]
		]
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Substrato:CreateBox:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:ZSize",
					"Value:="		, str(H)+"mm"
				],
				[
					"NAME:YSize",
					"Value:="		, "12mm"
				],
				[
					"NAME:XSize",
					"Value:="		, "6mm"
				],
				[
					"NAME:Position",
					"X:="			, "0mm",
					"Y:="			, "0mm",
					"Z:="			, "0mm"
				]
			]
		]
	])




oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Substrato:CreateBox:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:XSize",
					"Value:="		, "Wsub"
				],
				[
					"NAME:ZSize",
					"Value:="		, "H"
				],
				[
					"NAME:YSize",
					"Value:="		, "Lsub"
				]
			]
		]
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Substrato:CreateBox:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Position",
					"X:="			, "-Wsub/2",
					"Y:="			, "0mm",
					"Z:="			, "0mm"
				],
				[
					"NAME:ZSize",
					"Value:="		, "-H"
				]
			]
		]
	])
oEditor.CreateBox(
	[
		"NAME:BoxParameters",
		"XPosition:="		, "-2mm",
		"YPosition:="		, "0mm",
		"ZPosition:="		, "0mm",
		"XSize:="		, "3.5mm",
		"YSize:="		, "12mm",
		"ZSize:="		, "1mm"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Box1",
		"Flags:="		, "",
		"Color:="		, "(255 0 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, False,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DAttributeTab",
			[
				"NAME:PropServers",
				"Box1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Name",
					"Value:="		, "Microfita"
				],
				[
					"NAME:Material",
					"Value:="		, "\"copper\""
				],
				[
					"NAME:Color",
					"R:="			, 255,
					"G:="			, 0,
					"B:="			, 0
				]
			]
		]
	])


oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Microfita:CreateBox:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Position",
					"X:="			, "-Wfeed/2",
					"Y:="			, "0mm",
					"Z:="			, "0mm"
				],
				[
					"NAME:XSize",
					"Value:="		, "Wfeed"
				],
				[
					"NAME:YSize",
					"Value:="		, "Lsub"
				],
				[
					"NAME:ZSize",
					"Value:="		, "t"
				]
			]
		]
	])
oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "3mm",
		"YStart:="		, "0mm",
		"ZStart:="		, "-"+str(H)+"mm",
		"Width:="		, "-6mm",
		"Height:="		, "12mm",
		"WhichAxis:="		, "Z"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Rectangle1",
		"Flags:="		, "",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oDesign.Undo()
oEditor.CreateBox(
	[
		"NAME:BoxParameters",
		"XPosition:="		, "3mm",
		"YPosition:="		, "0mm",
		"ZPosition:="		, str(-H)+"mm",
		"XSize:="		, "-6mm",
		"YSize:="		, "12mm",
		"ZSize:="		, "-0.7mm"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Box1",
		"Flags:="		, "",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, False,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DAttributeTab",
			[
				"NAME:PropServers",
				"Box1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Name",
					"Value:="		, "Terra"
				],
				[
					"NAME:Material",
					"Value:="		, "\"copper\""
				],
				[
					"NAME:Color",
					"R:="			, 255,
					"G:="			, 0,
					"B:="			, 0
				]
			]
		]
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Terra:CreateBox:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Position",
					"X:="			, "-Wsub/2",
					"Y:="			, "0mm",
					"Z:="			, "-H"
				],
				[
					"NAME:XSize",
					"Value:="		, "Wsub"
				],
				[
					"NAME:YSize",
					"Value:="		, "Lsub"
				],
				[
					"NAME:ZSize",
					"Value:="		, "-t"
				]
			]
		]
	])
oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "1mm",
		"YStart:="		, "12mm",
		"ZStart:="		, str(t)+"mm",
		"Width:="		, "-0.817mm",
		"Height:="		, str(Wfeed)+"mm",
		"WhichAxis:="		, "Y"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Rectangle1",
		"Flags:="		, "",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DAttributeTab",
			[
				"NAME:PropServers",
				"Rectangle1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Name",
					"Value:="		, "Porta1"
				],
				[
					"NAME:Color",
					"R:="			, 0,
					"G:="			, 255,
					"B:="			, 255
				]
			]
		]
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Porta1:CreateRectangle:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Position",
					"X:="			, "-Wfeed/2",
					"Y:="			, "Lsub",
					"Z:="			, "t"
				],
				[
					"NAME:XSize",
					"Value:="		, "Wfeed"
				],
				[
					"NAME:ZSize",
					"Value:="		, "-(2*t+H)"
				]
			]
		]
	])
oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, "-1mm",
		"YStart:="		, "0mm",
		"ZStart:="		, str(t)+"mm",
		"Width:="		, "-0.817mm",
		"Height:="		, str(H)+"mm",
		"WhichAxis:="		, "Y"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Rectangle1",
		"Flags:="		, "",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DAttributeTab",
			[
				"NAME:PropServers",
				"Rectangle1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Name",
					"Value:="		, "Porta2"
				],
				[
					"NAME:Color",
					"R:="			, 0,
					"G:="			, 255,
					"B:="			, 255
				]
			]
		]
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Porta2:CreateRectangle:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Position",
					"X:="			, "-Wfeed/2",
					"Y:="			, "Lsub",
					"Z:="			, "t"
				],
				[
					"NAME:XSize",
					"Value:="		, "Wfeed"
				],
				[
					"NAME:ZSize",
					"Value:="		, "-(2*t+H)"
				]
			]
		]
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Porta1:CreateRectangle:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:Position",
					"X:="			, "-Wfeed/2",
					"Y:="			, "0mm",
					"Z:="			, "t"
				]
			]
		]
	])

oModule.AssignLumpedPort(
	[
		"NAME:1",
		"Objects:="		, ["Porta1"],
		"DoDeembed:="		, False,
		"RenormalizeAllTerminals:=", True,
		[
			"NAME:Modes",
			[
				"NAME:Mode1",
				"ModeNum:="		, 1,
				"UseIntLine:="		, True,
				[
					"NAME:IntLine",
					"Coordinate System:="	, "Global",
					"Start:="		, ["0mm","0mm","-0.817mm"],
					"End:="			, ["0mm","0",str(t)+"mm"]
				],
				"AlignmentGroup:="	, 0,
				"CharImp:="		, "Zpi",
				"RenormImp:="		, "50ohm"
			]
		],
		"ShowReporterFilter:="	, False,
		"ReporterFilter:="	, [True],
		"Impedance:="		, "50ohm"
	])
oModule.AssignLumpedPort(
	[
		"NAME:2",
		"Objects:="		, ["Porta2"],
		"DoDeembed:="		, False,
		"RenormalizeAllTerminals:=", True,
		[
			"NAME:Modes",
			[
				"NAME:Mode1",
				"ModeNum:="		, 1,
				"UseIntLine:="		, True,
				[
					"NAME:IntLine",
					"Coordinate System:="	, "Global",
					"Start:="		, ["0mm",str(Lsub)+"mm","-0.817mm"],
					"End:="			, ["0mm",str(Lsub)+"mm",str(t)+"mm"]
				],
				"AlignmentGroup:="	, 0,
				"CharImp:="		, "Zpi",
				"RenormImp:="		, "50ohm"
			]
		],
		"ShowReporterFilter:="	, False,
		"ReporterFilter:="	, [True],
		"Impedance:="		, "50ohm"
	])
oEditor.CreateRegion(
	[
		"NAME:RegionParameters",
		"+XPaddingType:="	, "Absolute Offset",
		"+XPadding:="		, "10mm",
		"-XPaddingType:="	, "Absolute Offset",
		"-XPadding:="		, "10mm",
		"+YPaddingType:="	, "Absolute Offset",
		"+YPadding:="		, "10mm",
		"-YPaddingType:="	, "Absolute Offset",
		"-YPadding:="		, "10mm",
		"+ZPaddingType:="	, "Absolute Offset",
		"+ZPadding:="		, "32mm",
		"-ZPaddingType:="	, "Absolute Offset",
		"-ZPadding:="		, "10mm"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Region",
		"Flags:="		, "Wireframe#",
		"Color:="		, "(143 175 143)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"vacuum\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, True,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "nan ",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.ChangeProperty(
	[
		"NAME:AllTabs",
		[
			"NAME:Geometry3DCmdTab",
			[
				"NAME:PropServers",
				"Region:CreateRegion:1"
			],
			[
				"NAME:ChangedProps",
				[
					"NAME:-Z Padding Data",
					"Value:="		, "2mm"
				]
			]
		]
	])

oModule.AssignRadiation(
	[
		"NAME:Rad1",
		"Faces:="		, [127,128,129,130,131,132],
		"IsFssReference:="	, False,
		"IsForPML:="		, False
	])


oModule = oDesign.GetModule("AnalysisSetup")
oModule.InsertSetup("HfssDriven",
	[
		"NAME:Setup1",
		"SolveType:="		, "Single",
		"Frequency:="		, "1GHz",
		"MaxDeltaS:="		, 0.02,
		"UseMatrixConv:="	, False,
		"MaximumPasses:="	, 12,
		"MinimumPasses:="	, 1,
		"MinimumConvergedPasses:=", 1,
		"PercentRefinement:="	, 40,
		"IsEnabled:="		, True,
		[
			"NAME:MeshLink",
			"ImportMesh:="		, False
		],
		"BasisOrder:="		, 1,
		"DoLambdaRefine:="	, True,
		"DoMaterialLambda:="	, True,
		"SetLambdaTarget:="	, False,
		"Target:="		, 0.3333,
		"UseMaxTetIncrease:="	, False,
		"PortAccuracy:="	, 2,
		"UseABCOnPort:="	, False,
		"SetPortMinMaxTri:="	, False,
		"UseDomains:="		, False,
		"UseIterativeSolver:="	, False,
		"EnhancedLowFreqAccuracy:=", False,
		"SaveRadFieldsOnly:="	, False,
		"SaveAnyFields:="	, True,
		"IESolverType:="	, "Auto",
		"LambdaTargetForIESolver:=", 0.15,
		"UseDefaultLambdaTgtForIESolver:=", True,
		"IE Solver Accuracy:="	, "Balanced",
		"InfiniteSphereSetup:="	, ""
	])
oModule.InsertFrequencySweep("Setup1",
	[
		"NAME:Sweep",
		"IsEnabled:="		, True,
		"RangeType:="		, "LinearCount",
		"RangeStart:="		, "1.8GHz",
		"RangeEnd:="		, "3.2GHz",
		"RangeCount:="		, 601,
		"Type:="		, "Interpolating",
		"SaveFields:="		, False,
		"SaveRadFields:="	, False,
		"InterpTolerance:="	, 0.5,
		"InterpMaxSolns:="	, 250,
		"InterpMinSolns:="	, 0,
		"InterpMinSubranges:="	, 1,
		"InterpUseS:="		, True,
		"InterpUsePortImped:="	, False,
		"InterpUsePropConst:="	, True,
		"UseDerivativeConvergence:=", False,
		"InterpDerivTolerance:=", 0.2,
		"UseFullBasis:="	, True,
		"EnforcePassivity:="	, True,
		"PassivityErrorTolerance:=", 0.0001,
		"SMatrixOnlySolveMode:=", "Auto"
	])

#---------------------

espessura = str(espessura)+"mm"

oEditor.CreatePolyline(
    [
        "NAME:PolylineParametersFractal"+str(nome),
        "IsPolylineCovered:=", False,
        "IsPolylineClosed:=", True,
        criar_pontos(pontos),
        criar_segmentos(pontos),
        [
            "NAME:PolylineXSection",
            "XSectionType:=", "None",
            "XSectionOrient:=", "Auto",
            "XSectionWidth:=", espessura,
            "XSectionTopWidth:=", espessura,
            "XSectionHeight:=", espessura,
            "XSectionNumSegments:=", "0",
            "XSectionBendType:=", "Corner"
        ]
    ],
    [
        "NAME:Attributes",
        "Name:=", "PolylineCesaro"+str(nome),
        "Color:=", "(255 0 0)",
        "MaterialValue:=", "\"copper\"",
        "SolveInside:=", False,
    ]
)

oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, pontos[0][0],
		"YStart:="		, pontos[0][1],
		"ZStart:="		, "0mm",
		"Width:="		, "t",
		"Height:="		, "-esp",
		"WhichAxis:="		, "Y"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Fractal"+str(nome),
		"Flags:="		, "",
		"Color:="		, "(255 0 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, False,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.SweepAlongPath(
	[
		"NAME:Selections",
		"Selections:="		, "Fractal"+str(nome)+",PolylineCesaro"+str(nome),
		"NewPartsModelFlag:="	, "Model"
	],
	[
		"NAME:PathSweepParameters",
		"DraftAngle:="		, "0deg",
		"DraftType:="		, "Extended",
		"CheckFaceFaceIntersection:=", False,
		"TwistAngle:="		, "0deg"
	])

#------------------------------------------------
oEditor.CreatePolyline(
    [
        "NAME:PolylineParametersFractal"+str(nome),
        "IsPolylineCovered:=", False,
        "IsPolylineClosed:=", True,
        criar_pontos(pontosn1),
        criar_segmentos(pontosn1),
        [
            "NAME:PolylineXSection",
            "XSectionType:=", "None",
            "XSectionOrient:=", "Auto",
            "XSectionWidth:=", espessura,
            "XSectionTopWidth:=", espessura,
            "XSectionHeight:=", espessura,
            "XSectionNumSegments:=", "0",
            "XSectionBendType:=", "Corner"
        ]
    ],
    [
        "NAME:Attributes",
        "Name:=", "PolylineCesaro"+str(nome+1),
        "Color:=", "(255 0 0)",
        "MaterialValue:=", "\"copper\"",
        "SolveInside:=", False,
    ]
)

oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, pontosn1[0][0],
		"YStart:="		, pontosn1[0][1],
		"ZStart:="		, "0mm",
		"Width:="		, "t",
		"Height:="		, "-esp",
		"WhichAxis:="		, "Y"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Fractal"+str(nome+1),
		"Flags:="		, "",
		"Color:="		, "(255 0 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, False,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.SweepAlongPath(
	[
		"NAME:Selections",
		"Selections:="		, "Fractal"+str(nome+1)+",PolylineCesaro"+str(nome+1),
		"NewPartsModelFlag:="	, "Model"
	],
	[
		"NAME:PathSweepParameters",
		"DraftAngle:="		, "0deg",
		"DraftType:="		, "Extended",
		"CheckFaceFaceIntersection:=", False,
		"TwistAngle:="		, "0deg"
	])

#---------------------------------------------------------
oEditor.CreatePolyline(
    [
        "NAME:PolylineParametersFractal"+str(nome+2),
        "IsPolylineCovered:=", False,
        "IsPolylineClosed:=", True,
        criar_pontos(pontosn3),
        criar_segmentos(pontosn3),
        [
            "NAME:PolylineXSection",
            "XSectionType:=", "None",
            "XSectionOrient:=", "Auto",
            "XSectionWidth:=", espessura,
            "XSectionTopWidth:=", espessura,
            "XSectionHeight:=", espessura,
            "XSectionNumSegments:=", "0",
            "XSectionBendType:=", "Corner"
        ]
    ],
    [
        "NAME:Attributes",
        "Name:=", "PolylineCesaro"+str(nome+2),
        "Color:=", "(255 0 0)",
        "MaterialValue:=", "\"copper\"",
        "SolveInside:=", False,
    ]
)

oEditor.CreateRectangle(
	[
		"NAME:RectangleParameters",
		"IsCovered:="		, True,
		"XStart:="		, pontosn3[0][0],
		"YStart:="		, pontosn3[0][1],
		"ZStart:="		, "0mm",
		"Width:="		, "t",
		"Height:="		, "-esp",
		"WhichAxis:="		, "Y"
	],
	[
		"NAME:Attributes",
		"Name:="		, "Fractal"+str(nome+2),
		"Flags:="		, "",
		"Color:="		, "(255 0 0)",
		"Transparency:="	, 0,
		"PartCoordinateSystem:=", "Global",
		"UDMId:="		, "",
		"MaterialValue:="	, "\"copper\"",
		"SurfaceMaterialValue:=", "\"\"",
		"SolveInside:="		, False,
		"ShellElement:="	, False,
		"ShellElementThickness:=", "0mm",
		"IsMaterialEditable:="	, True,
		"UseMaterialAppearance:=", False,
		"IsLightweight:="	, False
	])
oEditor.SweepAlongPath(
	[
		"NAME:Selections",
		"Selections:="		, "Fractal"+str(nome+2)+",PolylineCesaro"+str(nome+2),
		"NewPartsModelFlag:="	, "Model"
	],
	[
		"NAME:PathSweepParameters",
		"DraftAngle:="		, "0deg",
		"DraftType:="		, "Extended",
		"CheckFaceFaceIntersection:=", False,
		"TwistAngle:="		, "0deg"
	])
